### ISSUE TITLE
[Feature Request] Start stream right after activating

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#15]
**Describe the solution you'd like**
It would be quite nice if we could click on a "start" button in the modal that pops up right after you've solved the captcha and activated the stream to start the stream right away.

**Additional context**
I have also noticed some bugs that I haven't gotten around to describing properly yet. I'll try finding a fitting description soon to submit it as a proper issue.

**Feedback**
I absolute love the application by the way. It makes using BurningSeries so much more comfortable.

**Comment by DatL4g** [comment]
Neat little idea, will be available in the next release

**Comment by ngelus** [comment]
Thank you DATL4G

**Comment by DatL4g** [comment]
## Added feature

Watch button is clickable under this conditions only:

- Hoster is supported
- When activating multiple in a row:
  - **No** different series other than the inital
  - **No** different season other than the initial
  - **No** different language other than the initial
