### ISSUE TITLE
[BUG] Activating a host crashes the app

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#16]
**Describe the bug**
App crashes when trying to activate streamer "voe.sx"

**To Reproduce**
1. Select a series (For me it was In/Spectre)
2. Select an episode (For me S2E2)
3. Click on "Activate"
4. Scroll down on the webpage
5. Click on the play-symbol

**Expected behavior**
The episode should be activated.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 12
 - AppVersion: 4.1.0

**Additional notes:**
This was still working in 4.0.0 by the way. I rolled back to that in the meantime. 
Love the new Design by the way.

**Comment by DatL4g** [comment]
Seems like it broke in the last update, will provide a bug fix version (4.1.1) soon

However it looks like the activation still works (sometimes)

**Comment by ngelus** [comment]
No problem Datl4g. You're doing the lord's work by writing this app for free. And we can still use 4.0.0 anyways. Don't stress yourself. :D
