### ISSUE TITLE
[BUG] Error please try again later

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#18]
**Describe the bug**
Sorry to bother you again Datl4g, but whenever I open the App now it just tells me "Error please try again later".

**To Reproduce**
1. Open the App
2. Error appears

**Expected behavior**
App opens and let's me search for series.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 12
 - Version 4.1.1

**Comment by DatL4g** [comment]
Seems like there is a lot more traffic currently and my server can barely keep up with it.
Already second time this week (#17)

Restarted the server, should work again.
Can't afford a server upgrade yet, if anyone want's to support go ahead: https://github.com/sponsors/DATL4G/
25$ Needed per month

Will pin this as will probably happen from time to time

**Comment by DatL4g** [comment]
Until then anyone can just write a message here (and link me) and I will restart the server

**Comment by ngelus** [comment]
@DATL4G still down by the way. I don't think I can pay a monthly 25$. I could do 5$ monthly, But that wouldn't solve the issue...
But I guess we gotta start supporting this somehow, so I might become your first sponsor this evening.

**Comment by DatL4g** [comment]
@ngelus restarted server, works again.

And you don't have to pay the whole 25$ of course.
We can get there by small steps wether it's 5$ or "only" 1$.
In the end y'all profit by supporting the project.

**Comment by ngelus** [comment]
@DATL4G here ya go. I'm officially a sponsor now.

**Comment by DatL4g** [comment]
@ngelus I've seen it, thank you very much!
You may even get more features in later releases 😉

**Comment by ngelus** [comment]
I get the error again when trying to go to search.

**Comment by DatL4g** [comment]
Should work just tested

**Comment by ngelus** [comment]
> Should work just tested 

Nice. Thank you datl4g

**Comment by ngelus** [comment]
Sorry to disturb you, but I think the server might be down again.

**Comment by ngelus** [comment]
Oh no... Down again. Sorry.

**Comment by Erex2499** [comment]
Vielen Dank für die gute App

**Comment by ngelus** [comment]
Sorry to bother you again. I think the server is down. 😖

**Comment by ngelus** [comment]
Nevermind. I can reach it now.

**Comment by DatL4g** [comment]
> Nevermind. I can reach it now.

Yes I'm just fast ;)

**Comment by ngelus** [comment]
> > Nevermind. I can reach it now.
> 
> Yes I'm just fast ;)

Ye xD

**Comment by ngelus** [comment]
yo @DATL4G . next version when? :D

**Comment by DatL4g** [comment]
@ngelus not sure there's currently no roadmap for new features or improvements

creating a release only for PIP play/pause isn't worth it

**Comment by ngelus** [comment]
> @ngelus not sure there's currently no roadmap for new features or improvements
> 
> creating a release only for PIP play/pause isn't worth it 

Hmm... That is true.

**Comment by ngelus** [comment]
@DATL4G server might be down again

**Comment by apisword** [comment]
@DATL4G pls restart ❤️

**Comment by operationairstrike** [comment]
@DATL4G Server restart needed, app not loading 💀

**Comment by operationairstrike** [comment]
Hey it's not working again, I have a new idear how you could make this a bit better. What about automatically restarting the server every 60 mins or 6h or 12h or 24h ?

**Comment by operationairstrike** [comment]
Thanks

**Comment by marek22k** [comment]
I think it needs a restart again.

And thanks for you work!

**Comment by MayorMoonay** [comment]
Hey, it's not working for me right now, maybe a restart will help.

**Comment by MayorMoonay** [comment]
@DATL4G could you restart quickly please. Sorry to bother.

**Comment by ngelus** [comment]
Yo @DATL4G . I think might need a restart:
![Screenshot_2023-04-02-19-13-17-31_ca6ac5fff584d816cd4bcb1f7bcb363c.jpg](https://user-images.githubusercontent.com/25223259/229368289-e7b95e58-aa05-4401-84fb-c2e144fa9668.jpg)

**Comment by DatL4g** [comment]
@ngelus done

**Comment by ngelus** [comment]
> @ngelus done

Ty @DATL4G

**Comment by frutch** [comment]
@DATL4G so without a restart everyone gets the error message or is it just me since a couple of days?

**Comment by DatL4g** [comment]
@frutch everyone gets that error message.

seems like there is a lot more traffic again lately which causes the downtime

**Comment by marek22k** [comment]
Out of interest: Why does the app need a centralized server? Can't the app itself extract the data from the website?

**Comment by DatL4g** [comment]
@marek22k to get it working in the app, it needs to access bs.to directly which is blocked in most people network

it's possible to work around that by using dns over https with a provider like cloudflare but somehow it's not really working in the app (and I'm clueless why)

so the app only needs a server for the streams (activating) and nothing else if DoH would work

in that case the server would have way less traffic and load and wouldn't need a restart

if anyone gets it working and provides a working example I could adapt it to the app and it would be more stable (java or kotlin is fine)

**Comment by marek22k** [comment]
In newer Android versions, you can now activate DoT without an additional app. Is there a way to turn off the proxy mode in the app? On the one hand, this would relieve the server and on the other hand, it would be faster for some people (for example me)?

**Comment by DatL4g** [comment]
@marek22k the connection must be done in the app, even when it's possible to setup DoT or DoH system-wide is it not practical for the user

**Comment by marek22k** [comment]
As I understand it, bs.to is just accessed in the app through a proxy (the centralized server) to bypass DNS hjacking. My question was if there is any way to disable this proxy? I think for users who use encrypted DNS or VPN on their smartphone this would be useful. It is understandable that the connection is made in the app and not in the standard browser, since the app must somehow extract the information. Have I understood something here?

**Comment by DatL4g** [comment]
@marek22k the server processes the data, it's not just a proxy
however the processing could be done on-device if bs.to can be accessed but we would need DoH or DoT for that

So the main problem could be fixed if the site scraping is done in the app with DoH, but I don't know how to setup the DoH and execute the Request with it

**Comment by operationairstrike** [comment]
Collab with someone?

**Comment by DatL4g** [comment]
@operationairstrike feel free to provide a working example or to contribute to the project, it's open source

**Comment by operationairstrike** [comment]
I needs a restart

**Comment by ngelus** [comment]
Yo @DATL4G can we have a restart please?
Thank you in advance. 😁

**Comment by ngelus** [comment]
Yo @DATL4G I think it's down again. Take your time :D

Btw; is it a good idea to promote this via social media, or did you want to keep this a little more concealed? I mean... I'd imagine this thing is in a gray area of the law. 

I already recommended this to some friends in hope that some of them would become sponsors. :D

**Comment by DatL4g** [comment]
@ngelus this app is for educational and learning purposes only, so I won't promote it.
However if you're a teacher and wanna show your class how things are done in production applications, you're free to do this ;)

**Comment by ngelus** [comment]
@DATL4G 

Well... Not a teacher. Just an instructor. And not one for applications, but system engineering instead.

I was just thinking of posting on Twitter, reddit and the likes as to attract more potential sponsors.

I guess given enough time this project will gain enough sponsors on its own and without any promotion. 😁

Just thought I could speed up the process.

Not like my tweets and reddit posts reach many people anyways... 😂

**Comment by ngelus** [comment]
@DATL4G No crashes or server issues for a while now it seems. Very stable. Love it.

**Comment by ngelus** [comment]
when's the next release @DATL4G ?

**Comment by DatL4g** [comment]
@ngelus this release is a bit tricky.

I have to fix some more things, test everything and I'm quite busy rn.

Additionally the new casting feature creates a little big problem.
I have to discuss with the F-Droid team if this is can be included or not, as usually they don't want you to include google-apis.
Maybe it's just a new anti-feature in F-Droid and everything is okay, maybe I have to remove it again to keep F-Droid Support.
Maybe I have to drop F-Droid Support, maybe I have to serve different versions, one for F-Droid and one on GitHub, this however would break F-Droid update compatibility and would require a lot more work.

As I said I don't have that much time right now, so I can't say anything regarding a release date.

**Comment by ngelus** [comment]
> @ngelus this release is a bit tricky.
> 
> I have to fix some more things, test everything and I'm quite busy rn.
> 
> Additionally the new casting feature creates a little big problem.
> I have to discuss with the F-Droid team if this is can be included or not, as usually they don't want you to include google-apis.
> Maybe it's just a new anti-feature in F-Droid and everything is okay, maybe I have to remove it again to keep F-Droid Support.
> Maybe I have to drop F-Droid Support, maybe I have to serve different versions, one for F-Droid and one on GitHub, this however would break F-Droid update compatibility and would require a lot more work.
> 
> As I said I don't have that much time right now, so I can't say anything regarding a release date.

No problem. Take your time. I'd really love this feature tho. And I can only speak for myself here, but i really don't use f-droid. I'd rather just download from GitHub 😁

But if you think f-droid is necessary, then I wouldn't be mad either.

Do as you think my guy 😁

**Comment by DatL4g** [comment]
Everyone please take a look here https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by ngelus** [comment]
Hey @DATL4G,
Haven't read you for quite a while now since the app has been working perfectly.

Just wanted to ask if you're still working on casting to TV, or if this feature will not be developed.

Wouldn't be a problem for me either way, but would still be really nice to have.

Also; wouldn't it be nice to have a "general" discussion thread to discuss little things like this?

Just an idea. 😁

**Comment by Foxxey** [comment]
I'm getting the same error

**Comment by Foxxey** [comment]
![Screenshot_2023-09-10-16-51-02-85_ca6ac5fff584d816cd4bcb1f7bcb363c](https://github.com/DATL4G/Burning-Series/assets/66215329/64fb3377-bb93-4ce9-9cc0-c377dc1354ed)

I am getting this error. Is this related? Neither the thumbnail is loading nor the video player...

**Comment by operationairstrike** [comment]
I always get it and need to do it by hand I think its bc of captchas

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
