### ISSUE TITLE
[Feature Request] json to import

### ISSUE THREAD

**Issue by Pantyhose-X** [DATL4G/BurningSeries-Android#2]
**Is your feature request related to a problem? Please describe.**
Do not build in any web resources.
Importing resources via `json`
just like a `web crawler`

Burning Series web server is closed, we can still use `json to import` other web server resources.
Without json import, BurningSeries-Android will be useless once the built-in web server is shut down.

**Describe the solution you'd like**
```
{
    "WebsiteSourceName": "BurningSeries",
    "WebsiteSourceType": 0,
    "WebsiteSourceUrl": "https://bs.to",
    "WebsiteUrlPattern": "",
    "concurrentRate": "",
    "customOrder":  ,
    "enabled": true,
    "enabledExplore": true,
    "exploreUrl": "
    "header": "
    "lastUpdateTime": ,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": ,
    "ruleBookInfo": {
      "author": "",
      "coverUrl": ". ",
      "intro": ".",
      "kind": " ",
      "videosname": "",
      "tocUrl": "Catalog"
    },
    "ruleContent": {
      "content": "",
      "nextContentUrl": "",
      "replaceRegex": ""
    },
    "ruleExplore": {
      "author": ".",
      "movieList": ".",
      "movieUrl": "",
      "coverUrl": "",
      "intro": ".",
      "name": "."
    },
    "ruleSearch": {
      "author": "",
      "bookList": "",
      "bookUrl": "data-log\n@js:\n//java.log(result);\n\njson=eval(\"(\"+result+\")\");\njson.mu.replace(/www/g,\"h\");\n",
      "checkKeyWord": "",
      "coverUrl": "",
      "intro": "div[role=\"text\"]@span.1@text",
      "kind": "",
      "lastChapter": ".c-text-line-text.0@text",
      "name": ".c-title-text@text##Latest Programs.*"
  },
    "ruleToc": {
      "chapterList": "#alllist ul li@a",
      "chapterName": "text",
      "chapterUrl": "href",
      "nextTocUrl": "text.Next page"
    },
    "searchUrl": "https://bs.to {{key}},{\"webView\":true}",
    "weight": 0
  },
```

**Comment by DATL4G** [comment]
Hey unfortunately I don't quite understand this feature request.
The app is intended to work with Burning-Series and no(t yet any) other service.
The import for another page(?) would not make sense as the code is exactly specified for Burning-Series.

If I misunderstood something or you want to explain it a bit more, please go ahead and do further explanation.

**Comment by Pantyhose-X** [comment]
> Hey unfortunately I don't quite understand this feature request. The app is intended to work with Burning-Series and no(t yet any) other service. The import for another page(?) would not make sense as the code is exactly specified for Burning-Series.
> 
> If I misunderstood something or you want to explain it a bit more, please go ahead and do further explanation.

Okay, maybe I misunderstood that
[ZY Player](https://github.com/cuiocean/ZY-Player) he is getting through the api

**Comment by DATL4G** [comment]
Yeah this app is intended to work with Burning-Series only.
It's not a player for any service and the code is too deeply integrated to change that.

Closing
