### ISSUE TITLE
[Feature Request] Keep scroll position 

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#20]
**Is your feature request related to a problem? Please describe.**
I have noticed a minor inconvenience when putting the app into the background / task switcher where it resets the scroll back to the top of the page. This also happens when I activate a host.

**Describe the solution you'd like**
Would it be possible to keep the scroll position more consistent in between actions?

**Describe alternatives you've considered**
I would contribute a fix myself if I wasn't so bad at Java and Kotlin xD

**Additional context**
I'm not inpatient and since this is just a minor inconvenience you don't have to rush this. If this isn't possible, then that's not a problem either. Just a little inconvenient. That's all.

**Comment by DatL4g** [comment]
I'll take a look what's possible

**Comment by DatL4g** [comment]
First step done in [a9d7fdd](https://github.com/DATL4G/BurningSeries-Android/commit/a9d7fdd3707832d59b08f486ad0f355f79f31d58)

This will not work when putting the app in background until https://github.com/arkivanov/Essenty/issues/86 is done
