### ISSUE TITLE
[BUG] Clicking on GitHub symbol doesn't work

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#24]
**Describe the bug**
Just a little bug.
When I open the app and tap on the GitHub symbol, then it tries to take me to DatL4g/BurningSeries, but the real repo is DatL4g/BurningSeries-Android

**To Reproduce**
1. Open the App
2. Tap on the GitHub symbol

**Expected behavior**
It should take you to the repo.

**Screenshots**
![Screenshot_2023-02-03-16-08-41-84_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/25223259/216637643-e407b7ba-76d8-450d-8bf4-994c1e41d4b5.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - Version 4.3.0

**Additional context**
As I said. This really just is a minor issue. Take your time solving this. :D

**Comment by DatL4g** [comment]
Will work in a couple of days or next week again.

I'll change the GitHub repo URL as it's no longer related to android only
