### ISSUE TITLE
AndroidTV: can't control video playback after controls fade away

### ISSUE THREAD

**Issue by DeBelsch** [DATL4G/BurningSeries-Android#26]
Thanks for the support for AndroidTV. I have a new issue, which is not dramatic, but it improves the usability.

Describe the bug:
When a video is started, the control for play, pause, skip 10 seconds and go 10 seconds back appaer and can be used to control. When the video is playing, after some seconds, these controls fade away and can't be displayed again, so the playback can't be controlled. Only way to "pause" is to press the back button to the menu.

1. Play a video
2. Wait until the controls disappear
3. Pressing of any button won't let reappear the controls

Expected behavior:
Pressing the "OK" (the button to engage)  should let reappaer the controls or/and would pause the video. Maybe even when pressing the "right arrow" button could let us skip 10 seconds and vise versa for "left arrow".

 Device:
 - Manufacturer: TCL
 - OS: Android TV
 - Version: unknown

Thanks for your work.

**Comment by stella1407** [comment]
Ich kann kein Englisch kenne mich nicht aus und meine burning series
deutsch android funktioniert nicht und meine lieblingsserie kann ich die 11
Staffel nur auf englisch sehen alle anderen waren auf deutsch voll blöd

DeBelsch ***@***.***> schrieb am Fr., 3. Feb. 2023, 22:33:
