### ISSUE TITLE
[BUG] Player stays blank. Doesn't play

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#29]
**Describe the bug**
Hi DatL4g. When I try watching something the player just stays black. Doesn't even show the running time or anything. Just the play button. The running time and the total time stay at 00.00.

**To Reproduce**
1. Click on some series
2. Click on some episode
3. Activate if needed
4. Player opens but stays blank / black.

**Expected behavior**
Video should start playing.

**Screenshots**
![Screenshot_2023-02-19-15-59-15-04_ca6ac5fff584d816cd4bcb1f7bcb363c.jpg](https://user-images.githubusercontent.com/25223259/219956199-24a51e41-08db-441f-a25a-b8b98ba8b6e0.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 13 / OxygenOS (latest)
 - Version 4.3.1 (latest)

**Additional context**
I have noticed, that bs.to has enabled HSTS. I was not able to visit bs.to using Firefox either today. I fixed that by enabling DoT (DNS over TLS) in my router this morning. I'm using cloudflare's 1.1.1.1 (one.one.one.one or 1dot1dot1dot1.cloudflare-dns.com). Now I can use bs.to in Firefox again. Maybe the rollout of TLS1.2 broke something on bs.to's side of things? I don't know. Just some additional context :D

**Comment by ngelus** [comment]
Completely reinstalling the app didn't help either by the way. I just tried.

**Comment by ngelus** [comment]
Little update to the situation: going back to version 4.3.0 solved the issue

**Comment by ngelus** [comment]
Thank you @DATL4G. I will try the new update this evening.

**Comment by ngelus** [comment]
@DATL4G didn't work. Still the same behavior as before.

**Comment by DatL4g** [comment]
@ngelus can't reproduce on any of my devices

Can you tell me a specific series and episode thats not working

**Comment by ngelus** [comment]
@DATL4G yea. Will do this evening. I am at work right now. But I get that issue with every episode of every series on version 4.3.1 and 4.3.2. I have tried 4 different series yesterday. I think I tried watching the series "Resident Alien" S2E2 when it happened yesterday. My solution was to roll back to 4.3.0.

**Comment by ngelus** [comment]
I also thought that I could fix this by deleting the apps storage and cache, but that didn't help either.

Coincidentally the issue started happening one day right after I've upgraded from Android 12 to Android 13.

But 4.3.0 still seems to work perfectly fine. Just no PiP. D:

**Comment by ngelus** [comment]
Is there any way of getting a stacktrace out of this that would help you diagnose this?

**Comment by DatL4g** [comment]
This doesn't create a stacktrace as it doesn't happen because of an exception

**Comment by ngelus** [comment]
Is there any other way I could help you diagnose this?

**Comment by DatL4g** [comment]
@ngelus Not really however I think I got it now.

I need more features or improvements for the next release, so if you have any ideas this would be a good oppertunity

**Comment by ngelus** [comment]
@DATL4G hmm... I don't really have any more Ideas right now. I did however find that the "Watch" button that appears in the modal every time I activate a episode is only some times working. Other times it's greyed out for some reason. Is this intended behaviour?

**Comment by ngelus** [comment]
@DATL4G would offline availability be difficult to implement?
You know... so that I can watch series I previously declared to be downloaded on the go without an internet connection?

**Comment by DatL4g** [comment]
@ngelus yes the watch button behavior is intended.

Download is impossible as this breaks the law in most countries, it would get removed very quickly

**Comment by ngelus** [comment]
@DATL4G hmm.. okay. well I don't have any other ideas yet tho. I'll create a new issue when something comes to mind :D

**Comment by ngelus** [comment]
@DATL4G Am I doing something wrong when the watch button is grayed out, or what is causing this?
I know it's intended, but it would be nice to know what triggers it to show or not show.

**Comment by DatL4g** [comment]
@ngelus It's greyed out because the video source could not be found.
Maybe it got removed from the hoster or the hoster itself is not supported.

I didn't wanna remove it as it indicates the user that even though they activated it, they cannot watch and have to activate another hoster

**Comment by ngelus** [comment]
@DATL4G okay. good to know :D

**Comment by ngelus** [comment]
@DATL4G 4.4.0 is great. Everything is working flawlessly so far.

Is there a possibility for us to get a play/pause button inside the Pip player in a future update?

**Comment by DatL4g** [comment]
@ngelus probably not as most devices have multiple icons in PIP mode already and  the play button is behind that

**Comment by ngelus** [comment]
@DATL4G Hmm. Aight. Firefox and YouTube must've figured out a complicated way to do that then. I understand some things are more difficult and others. Would've been a novelty / luxury thing to have anyways. Pip for your app works great as is anyways. 😁

**Comment by DatL4g** [comment]
@ngelus Adding the Play/Pause in PIP was easier than I thought. Done in [ed0ba15](https://github.com/DATL4G/Burning-Series/commit/ed0ba1502a3f91632672889d35989cc2403477b0)

Will be available in next release

**Comment by ngelus** [comment]
> @ngelus Adding the Play/Pause in PIP was easier than I thought. Done in [ed0ba15](https://github.com/DATL4G/Burning-Series/commit/ed0ba1502a3f91632672889d35989cc2403477b0)
> 
> Will be available in next release

Very cool @DATL4G . Thank you. :D
