### ISSUE TITLE
[Feature Request] Implement Provider to Cloudstream3

### ISSUE THREAD

**Issue by DoYouNotice** [DATL4G/BurningSeries-Android#3]
You might want to look into Cloudstream3 https://github.com/LagradOst/CloudStream-3
It basically does the same thing your app does and has a pretty good layout.
The app has multiple Providers from Different Languages, you could try add there the German one.
If you can add the Provider to Cloudstream3 that would be nice.

**Comment by DATL4G** [comment]
Unfortunately this won't be possible.
The API I built (using site scraping) does not contain enough information, thats needed for the app.

Additionally I have to bypass a captcha on the site to get video information
