### ISSUE TITLE
[BUG] Not loading

### ISSUE THREAD

**Issue by apisword** [DATL4G/BurningSeries-Android#33]
**Describe the bug**
App isnt loading series and films.

**To Reproduce**
1. Open the app.
2. Wont load.

**Expected behavior**
Show series and films.

**Screenshots**
![Screenshot_2023-03-11-16-37-31-607_dev.datlag.burningseries.jpg](https://user-images.githubusercontent.com/119858562/224493518-8359541e-eaa3-4433-b51a-a091d801a1f4.jpg) (german ui)

**Smartphone (please complete the following information):**
 - Device: Xioami 11T 5G
 - OS: MIUI 14.0.1 / Android 12
 - Version V 4.4.0

**Additional context**
No more information.

**Comment by DatL4g** [comment]
Same as #18 please read for more information (fixed now)

**Comment by apisword** [comment]
> Same as #18 please read for more information (fixed now)

Thanks
