### ISSUE TITLE
[BUG] Crashes when trying to play Episode

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#36]
**Describe the bug**
I watched two Episodes of a series and now when I try to play the 3rd it loads 1 sec and then crashes. Even after deleting cache.

**To Reproduce**
1. Open the app.
2. Search for Sexify
3. Choose German and the first Episode
4. Press the light blue button that says play eps3.

**Expected behavior**
Load the video and start playing it.

**Screenshots**
![Screenshot_2023-03-16-17-18-59-069_dev.datlag.burningseries.jpg](https://user-images.githubusercontent.com/127621147/225685120-0e16d276-89bd-4f33-ad00-cea1bb3e53d9.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T 5ag
 - OS: Android 12
 - Version: 4.4.0

**Additional context**
Nothing.

**Comment by operationairstrike** [comment]
@DATL4G Thank you so much for the fix❤️

**Comment by operationairstrike** [comment]
@DATL4G Can you push the APK with the fixes to F Droid?

**Comment by DatL4g** [comment]
@operationairstrike F-Droid triggers the build itself, usually about 2-3 days (may take longer) after I release a new version

**Comment by operationairstrike** [comment]
Ok so it will now automatically push it, like after 2-3 days commits get included. Or do you like need to say make a new release?

**Comment by DatL4g** [comment]
I create a new release here on GitHub, then a couple of days later they automatically create a new release on F-Droid.

**Comment by operationairstrike** [comment]
I see.
