### ISSUE TITLE
[BUG] Watch Button grayed out after selecting hoster.

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#37]
**Describe the bug**
After selecting streamtape or any other hoster it will only say continue but the watch button is gray, and not working.

**To Reproduce**
1. Open Sexify Series on the App
2. Click on 1. Series
3. Select 4. Episode
4. Select choose hoster.
5. Tap on play and solve captcha.
6. Error visible

**Expected behavior**
Save it and let me play it directly from the app and save it. After I tapped continue it like didn't save the hoster for the episode.

**Screenshots**
![Screenshot_2023-03-17-20-39-15-124_dev.datlag.burningseries.jpg](https://user-images.githubusercontent.com/127621147/226007383-8af8cb24-7b73-4d1f-81c3-476f2bcdeea6.jpg)

(German)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T 5G
 - OS: Android 13
 - Version: MIUI 14.0.1 Global

**Additional context**
Yeah please tell me what I'm doing wrong it fix it pls. Thanks.

**Comment by DatL4g** [comment]
This is an intended behavior.
Only if a streamable source is found, this button is available.
Usually this means the hoster is not supported or the video got deleted.

**Comment by operationairstrike** [comment]
Oh ok thanks.
