### ISSUE TITLE
[BUG] Play button grayed, out but Video and supported hoster is available. (Streamtape)

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#39]
**Describe the bug**
Like in my last issue about this, after selecting the hoster I still can't play it. But of I go to bs.to myself I can watch it after solving the captcha. So my assumption is that either there is a bug or like the app can't get around the capchas.

**To Reproduce**
1. Go to Sexify Episode 4 of Series 1
2. Click on play
3. Select stream tape hoster

**Expected behavior**
Find the existing video source and play it.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xioami 11T 5G
 - OS: Android 13
 - Version: 4.5.0

**Additional context**
Sorry for my issues, but I'm trying to improve the app for others.

**Comment by DatL4g** [comment]
Streamtape is not supported

**Comment by operationairstrike** [comment]
Why does it show up in the settings then?

**Comment by DatL4g** [comment]
Because I don't know which hoster is supported or not, as they change, get removed / newly added constantly.

**Comment by operationairstrike** [comment]
Hmm
