### ISSUE TITLE
[Feature Request] Streamtape Support

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#40]
**Is your feature request related to a problem? Please describe.**
Certain series are not watchable, bc streamtape isn't supported.

**Describe the solution you'd like**
Support for streamtape 

**Describe alternatives you've considered**
Idk

**Additional context**
Thanks for the fix, didn't change anything for me, but thanks all the same.❤️

**Comment by DatL4g** [comment]
Not (possible), I tried to add it, but didn't succeed.
You can try to add it yourself, I can give some brief info if you need it, but I won't add it

**Comment by operationairstrike** [comment]
Ok do that pls.
