### ISSUE TITLE
[Feature Request] Genres ausklappbar

### ISSUE THREAD

**Issue by FadeFx** [DATL4G/BurningSeries-Android#41]
Es wäre super praktisch, wenn die Genres unter Alle Serien standardmässig eingeklappt wären, also nur eine Genre Liste angezeigt würde und man dann das Genre das man ansehen möchte ausklappen könnte.

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
