### ISSUE TITLE
[BUG] Crashing when watching and not showing episodes now

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#45]
**Describe the bug**
Hey @DATL4G. Sorry to annoy you about this, but the app just crashed on me when I clicked on "watch" in the modal that pops up right after activating. Now it's not showing me any episodes anymore.

**To Reproduce**
1. Go to a series (ex. The Ancient Magus Bride)
2. Select the season (for me it was season 2)
3. Click on an Episode (Ep 3 for me)
4. Click on "Activate"
5. Solve your preferred hoster's captcha (for me voe.sx)
6. Wait for Modal to appear and click on "Watch"
7. App crashes
8. Kill app completely
9. Reopen App
10. Go back to the series you were just activating
11. No episodes are listed

**Expected behavior**
The App shouldn't crash when clicking the "Watch" button in the modal that pops up after activation.

Episodes should show up.

**Screenshots**
![Screenshot_2023-04-20-23-36-59-34_ca6ac5fff584d816cd4bcb1f7bcb363c.jpg](https://user-images.githubusercontent.com/25223259/233494515-d2b80777-ed0e-4908-be8f-3a0933f15264.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 13
 - Version: 4.6.0 (latest release)

**Additional context**
None.

**Comment by ngelus** [comment]
Hmm... I just wiped the app of my phone and reinstalled it. Atleast the episodes are showing up again.

I'll test the thing with the watch button in the modal crashing the app after this episode 😁

**Comment by operationairstrike** [comment]
Same thing for me

**Comment by ngelus** [comment]
It's all been good until now. Now I'm having the exact same problem again. Episodes list not loading after the app crashes when I pressed the "Watch" button. But i assume the commit just fixed that. 😁
