### ISSUE TITLE
[BUG] Watch causing app crash

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#46]
**Describe the bug**
App crahes after pressing Watch on Vidoza.

**To Reproduce**
1. Go to 4400 (2021)
2. Click on Play Ep. 1
3. Click on Vidoza and solve Captcha.
4. Press watch!

**Expected behavior**
Start playing the episode.

**Screenshots**
![Screenshot_2023-04-21-07-05-01-714_dev.datlag.burningseries.jpg](https://user-images.githubusercontent.com/127621147/233545264-538b73ef-b297-45b8-8605-f6cc8cf459bb.jpg)

**Smartphone (please complete the following information):**
 - Device: Xioami 11T
 - OS: Android 13
 - Version: MIUI 14.0.2

**Additional context**

**Comment by DatL4g** [comment]
Please just comment if an issue already exists next time with the following information:

> Series: 4400 (2021)
> Episode 1
> Hoster: Vidoza

Makes it easier for me to keep track of present bugs
