### ISSUE TITLE
[Feature Request] Enhancing Android App Usability for Android TV Devices

### ISSUE THREAD

**Issue by entchen66** [DATL4G/BurningSeries-Android#47]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is related to the usability of the Android app on Android TV. Currently, navigating through the app using a remote control is not intuitive, and it is difficult to determine which elements are highlighted while clicking through the app. This negatively affects the user experience and makes it frustrating to use the app on Android TV.

**Describe the solution you'd like**
I would like to propose a redesign of the app's user interface, specifically tailored for Android TV. This redesign should include the following improvements:

- [ ]  Clear visual indicators for the currently highlighted element, such as distinct color changes, borders, or other visual cues to help users easily identify the selected item.
- [ ]  Improved navigation and remote control support, ensuring seamless and intuitive interaction with the app using directional buttons (up, down, left, right) and other standard remote control buttons (select, back, etc.).
- [ ]  Optimization of the layout for larger screens, taking into account the typical viewing distance of users on Android TV, ensuring that all text, images, and interface elements are easily visible and accessible.
- [ ]  Implementing a simplified and more streamlined menu system to help users quickly find and access desired content or features.

**Describe alternatives you've considered**
One alternative solution could be to create a separate, dedicated Android TV app version, optimized specifically for Android TV devices. However, this might require additional development resources and could lead to inconsistencies between the Android and Android TV app versions.

Another alternative could be to implement a context-aware interface that adapts its layout, navigation, and appearance based on the type of device it's being used on. This would ensure a consistent experience across different devices but might require significant changes to the existing app's structure and design.

**Additional context**
Improving the app's usability on Android TV will not only enhance the user experience for existing users but also attract new users who primarily use their Android TV devices for consuming content. As Android TV continues to grow in popularity, ensuring a seamless and enjoyable experience on this platform is crucial for the app's success.

In conclusion, as a fellow anime fan, I'd like to express my heartfelt gratitude to all the developers for your phenomenal work on this fan-made project. You've managed to bring the captivating world of the Burning Series collection to life, making it easily accessible on Android TV for fans like us. Your unwavering passion and dedication have truly elevated our anime-watching experience, allowing us to enjoy our favorite series on a whole new platform.

Being part of this fantastic community, I'm excited to see how the project continues to flourish under your guidance. Your continuous efforts to improve the app make a significant difference, and I'm grateful for the opportunity to contribute to its development with this feature request. Keep up the outstanding work, and thank you once again for everything you do for us, the anime enthusiasts!

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
