### ISSUE TITLE
[BUG] List of Episodes weirdly indented

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#49]
**Describe the bug**
Watching AOT S3 right now and the episodes list is a little weird right now. Some episodes are indented a lot more than the others. Shifted / aligned more to the right basically.

**To Reproduce**
1. Go to Attack on Titan Season 3
2. Scroll down
3. Witness the weirdness 

**Expected behavior**
Correct alignment.

**Screenshots**
![Screenshot_2023-04-22-22-45-58-99_ca6ac5fff584d816cd4bcb1f7bcb363c.jpg](https://user-images.githubusercontent.com/25223259/233806052-361d0618-4536-48f0-a0b5-30bafbc93c57.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 13
 - Version: 4.6.1 (currently the latest version)

**Additional context**
This isn't too much of a problem. Just wanted to point it out.

**Comment by DatL4g** [comment]
Seems to be a internal compose bug, nothing I can do about rn

**Comment by ngelus** [comment]
Okay. It's not a huge problem anyways.

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
