### ISSUE TITLE
[BUG] App crashes when trying to watch an already activated episode

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#50]
**Describe the bug**
For some reason the app just randomly decides to crash when I try watching an episode that's already activated now.

**To Reproduce**
1. Go to some series
2. Click on an episode 
3. Experience a crash

**Expected behavior**
The app shouldn't crash

**Screenshots**
https://user-images.githubusercontent.com/25223259/233867494-861d23cd-f085-4e95-b7d9-1fabd82be3e1.mp4

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 13
 - Version: 4.6.1 (latest)

**Additional context**
I have attached a small video showcasing the error. I hope this gets properly embedded on GitHub. If not, then I'll attach a hidden YouTube link later instead.

**Comment by ngelus** [comment]
https://youtube.com/shorts/h6HH4x_EN18

Here's the unlisted YouTube link.

**Comment by ngelus** [comment]
Oh well... It unexpectedly also just started working fine again, but I've experienced this on multiple occasions. Maybe this is worth looking into. Maybe it isn't. Do with this information whatever you deem is best. 😁

**Comment by ngelus** [comment]
Problem didn't occur for quite a while now. I think you can close the issue and reopen it when needed now. :D

**Comment by DatL4g** [comment]
@ngelus i'll close as soon as a new version is available which provides an error log.

This keeps track of / reminds me of this change

**Comment by ngelus** [comment]
Alright
