### ISSUE TITLE
open stream with external app [Feature Request]

### ISSUE THREAD

**Issue by SoerenDaenekas** [DATL4G/BurningSeries-Android#52]
Why?

I use apps which redirect videos streams to Chromecast/miracast. Or i download the video for later use.

**Describe the solution you'd like**

I would like to be able to open the video stream with VLC or other apps. VLC allows streaming to Chromecast.

**Describe alternatives you've considered**

There aren't any good direct stream-grabbers for Android.

**Comment by DatL4g** [comment]
Not possible as some hoster require additional information to play the media and videoplayer apps have not standardized it.
However casting is possible using the according [media package](https://developer.android.com/reference/androidx/media3/cast/package-summary), but I've never implemented this.

Pull Requests are welcome

**Comment by ngelus** [comment]
> Not possible as some hoster require additional information to play the media and videoplayer apps have not standardized it. However casting is possible using the according [media package](https://developer.android.com/reference/androidx/media3/cast/package-summary), but I've never implemented this.
> 
> Pull Requests are welcome

I'm very excited for the implementation of this feature.
