### ISSUE TITLE
[Amazon Fire TV stick support]

### ISSUE THREAD

**Issue by Knoxyzz** [DATL4G/BurningSeries-Android#55]
Support für Amazon Fire Tv Stick wäre mega. Da ich ein Iphone besitze und ich mal annehme dass es keine BS Apps zum sideloaden für IOS gibt wäre der fire tv stick support cool. Ich kann die App öffnen und nach serien suchen jedoch kann ich dann nicht auf play drücken oder die Sprache mit den bittons ändern.

Mfg

**Comment by High-village** [comment]
Ja crashed leider öfters noch auf dem Fire TV und starten einer Serie klappt nicht, Navigation etc sollte sonst eig stimmen so weit. Wäre top wenn man da vll noch drüber schauen könnte da wohl die meisten nen Fire TV (Stick) haben als Android TV.
Nice App auf jeden Fall, habe sie auch in meinem inoffiziellem BS Discord Server gepostet. Falls du Bock hast da sonst mal vorbeizuschauen: https://discordapp.com/invite/HYC3xaR

**Comment by DatL4g** [comment]
@High-village can you provide a crash log from app settings please else it's hard to debug for me as I don't own a fire tv stick

**Comment by High-village** [comment]
Hab keine solche Option gefunden auf meinem Fire TV für die App's hast du eig. nur die Möglichkeit Cache und/oder Daten zu löschen resp. App zu deinstallieren.

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
