### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by motareks** [DATL4G/BurningSeries-Android#58]
Hi, wenn ich Streaming Quellen aktivieren möchte, lädt der interne Browser die Seite nicht. Jedes Mal erscheint die Fehlermeldung "Fehler, bitte Versuche es später erneut." Der einzige Player der ohne Aktivierung funktioniert ist VOE.

**Comment by motareks** [comment]
PS: I am using the app on Fire TV Stick.

**Comment by DatL4g** [comment]
Aktiviere es am besten über einen PC mit DNS-Over-Https und der Extension

**Comment by motareks** [comment]
Hi, sorry für die rückfrage, gibt es dazu evtl. eine Anleitung bzw. hast du mehr Infos für mich? Bin in dem Gebiet leider kein Experte...
