### ISSUE TITLE
5.x REWORK in progress

### ISSUE THREAD

**Issue by DatL4g** [DATL4G/BurningSeries-Android#62]
@IJaqenHgarI 
@PalmarHealer 
@ngelus
and whoever is interested in this project

I finally have time to work on this again.
Additionally I prepared some underlying work and dependencies the past months, meaning it will get even better ;)

It will take some time to reach a "working" state but keep an eye on the [5.x branch](https://github.com/DatL4g/Burning-Series/tree/5.x) and stay tuned

**Comment by DatL4g** [comment]
To keep thes issue board clean and fresh I'll close all open issues now.
Most (if not all of them) will be done in 5.x anyway

**Comment by High-village** [comment]
sweet. great to see that you have some time and energy again to put into this project. o/

**Comment by ngelus** [comment]
I am very excited to see what features you'll implement.

**Comment by DatL4g** [comment]
New version out now https://github.com/DatL4g/Burning-Series/releases/tag/v5.0.0!

**Comment by marek22k** [comment]
Thanks for the amazing App!

What is the reason that the App is no longer on F-Droid? Will it be in IzzyOnDroid (@IzzySoft)?

**Comment by ngelus** [comment]
Thank you @DatL4g . The new version is awesome 😎👍

**Comment by IzzySoft** [comment]
> Will it be in IzzyOnDroid

No. First the APK size is more than twice the per-app limit, and second it comes with…

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cast (/com/google/android/gms/cast): NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeComp
* Google App Engine (/com/google/appengine): NonFreeNet
* Cloud Audit Logs (/com/google/cloud/audit): Tracking
* Google Cloud Logging Client for Java (/com/google/cloud/logging): NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* firebase-firestore (/com/google/firebase/firestore): NonFreeDep,NonFreeNet

9 offenders.
```

Those marked `NonFreeComp`  will also keep it from becoming available at F-Droid.org.

**Comment by Sebtasticxz** [comment]
Läuft trotzdem Super auf AndroidTv besser als die 4.7er. Das einzige was stört, das keine App Verküpfung mehr auf dem TV angezeigt wird und man es über die Einstellungen -> Apps öffnen muss.
