### ISSUE TITLE
[BUG] APK crashes idk the cause

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#64]
**Describe the bug**
App crashes randomly when searching.

**To Reproduce**
1. Open app
2. Search for something

**Expected behavior**
Not crash.

**Screenshots**
 None.

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T 5G
 - OS: Android 13
 - Version: 6.0

Did you change the logo to blue? Black looked better.

**Comment by DatL4g** [comment]
When is it crashing exactly?

- When you go to the Search Tab?
- When you are on the search tab and enter something in the search bar at the top?
  - What did you type for example

I updated the android packages in the latest release to provide crash logs, please download and install it again and then

- Reproduce the crash
- Open the app again, so it can upload the crash

**Comment by operationairstrike** [comment]
It's random but when using the search or just using the app fast.

**Comment by operationairstrike** [comment]
When you search for something.

**Comment by operationairstrike** [comment]
Thanks
