### ISSUE TITLE
[Feature Request] Netflix Trending and exclude categories from main page

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#65]
**Is your feature request related to a problem? Please describe.**
The starting site with the suggestions and updated has too much animes and it's not really useful bc there's nothing interesting being shown. And I guess like things that many people watch will also be more popular on here.

**Describe the solution you'd like**
A settings tab where you can select categories to exclude and maybe show trending stuff on start page, for that Netflix could be used but as well other statistics sites.

**Describe alternatives you've considered**
Just a toggle to exclude anime.

Thanks for the crash fix.

**Comment by DatL4g** [comment]
Nothing I can do about.

The service doesn't collect any personal information and can't interact with the source even if it would.
The home episodes and series depend on the https://bs.to front page, all you see there is all I can show.

**Comment by operationairstrike** [comment]
Thanks all the same for responding 💪🏼.
