### ISSUE TITLE
How to use Browser Extension and Desktop doesn't start.

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#66]
So first how does the extension work I installed it in Firefox and gave it all permissions but I couldn't figure out how it works.

And then I tried installing the desktop version and it successfully installed but after installing it didn't show up on the desktop and as well didn't show up when using the search bar.

I'm using the newest version of Windows 11.

If you need more information ask me.

Thanks for the updates 💪🏼.

**Comment by DatL4g** [comment]
## Browser

Basically you just have to go to https://bs.to then, go to any series and episode of your choice, select a hoster (solve the captcha, if any) and then it will be activated after a few seconds (blue indicator then on the hoster selection).

Haven't tested the Firefox version, but the Chromium version is basically the same and works without a doubt.

## Desktop

You have to link it to your desktop or the start menu yourself.
Locate the application installation path (Probably in `C:\Program Files\Burning-Series`)
Right click the `.exe` and add it to your dektop or to your start menu

Nothing I can do about this setup now, as compose doesn't give enough options to edit the installer

**Comment by operationairstrike** [comment]
Thanks can you maybe include this in the readme

**Comment by operationairstrike** [comment]
@DatL4g how does the browser extension interact with the app? Do I need to connect something or is it like voe will whitelist me kinda
