### ISSUE TITLE
[Feature Request] Toggle watched status manually

### ISSUE THREAD

**Issue by Slluxx** [DATL4G/BurningSeries-Android#68]
Since watch a lot of shows on my pc, id like to set the watched status in the app manually for entire seasons aswell as single episodes. It would make tracking a lot easier. 

Also, i feel like a tap on any icon in the bottom bar should always lead to the page it tells you. Currently, on any page (home, fav and search) you can click on different shows that will always reopen if you switch between the pages. That can be **very** confusing if you have shows opened on two or three pages.

Id probably remove the search page alltogether and just display a search bar at the top of home and favorites. On the home page it would search all shows and on the favorites page it would only filter those. It would be more consitent with layouts we already know (google, amazon and what not).

Default settings for language and what not would also be nice.

I also noticed that if i set a language on my favorites it is getting saved, however if i search for the same show, the language is set to the default.

**Comment by DatL4g** [comment]
The watch status can be toggled by double clicking/tapping the episode in the upcoming release.
Additionally there will be a new indicator for the pending or next episode to watch or to switch to the next season if the last episode is finished.

The navigation already follows the best practices, however it will now be possible to go the desired page even if a series was selected by simply clicking the tab again.

The search follows the best practices as well, you are right that a search in the home would be a lot more convinient and overall nice to use, however https://bs.to doesn't offer a nice search or pagination option, and just displays all series they have.
That can cause long loading times to users and just would lead to more confusion if the home got loaded properly but the search isn't available.

Saving special options like default language etc and settings in general can't be done unless `Proto Datastore` can be used multiplatform.

**Comment by Slluxx** [comment]
> Saving special options like default language etc and settings in general can't be done unless Proto Datastore can be used multiplatform.

How do you save the favorite status? And why rely on Proto Datastore? You could have users opt-in to firebase or any other cloud based database. Since you have to be online anyway to watch shows, that shouldnt be a problem and allow for a wider range of features.

Since you are using a webview, it might also be possible to (ab)use it and use webstorage to save data on any plattform. You should be able to access, read and modify it without actually having to display it.

> The search follows the best practices as well, you are right that a search in the home would be a lot more convinient and overall nice to use, however https://bs.to/ doesn't offer a nice search or pagination option, and just displays all series they have.
That can cause long loading times to users and just would lead to more confusion if the home got loaded properly but the search isn't available.

Once you figured out how to get basic storage, you can easily cache the entire list and update it async. Some kind of indicator could show that you are fetching the titles while being able to search through the cache. The only downside would be that a show might be removed from BS. Allthough thats highly unlikely and you could just check and display some kind of message.

**Comment by DatL4g** [comment]
I don't like any of these ideas.

The firebase databases is handled completely anonymous for a good reason, not only the original webiste is not accessable in many countries due to law enforcements but if I add a user management I have to add many many features to meet european requirements and might even have to reveal user information, which I don't want to do.

So it has to be an offline storage, using the webstorage to store data sounds absolutely terrible and sqlite database (used for series) isn't a viable option since it's not flexible enough.

The search list is already cached but you missed the point that this is a big network request. If you're traveling for example you rely on mobile network which is not unlimited for a lot of people so I'd rather not waste that if not necessary.

Having an extra page for the search is not **THAT BAD**

**Comment by Slluxx** [comment]
I agree that abusing webview's webstorage is terrible and that a firebase connection complicates things a lot but why is sqlite not flexible enough? What is there that you want to do that doesnt work with sqlite?
