### ISSUE TITLE
[Feature Request] Make descriptions unfoldable

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#70]
**Is your feature request related to a problem? Please describe.**
I can only read small parts of the description and don't really have a clue what to expect.

**Describe the solution you'd like**
A button that you can press to read the full description provided by bs.to

**Describe alternatives you've considered**
A Button to open the bs.to site to show the description.

**Additional context**
![Screenshot_2024-02-05-17-15-44-917_dev.datlag.burningseries.jpg](https://github.com/DatL4g/Burning-Series/assets/127621147/5a5698bc-918a-46da-804a-a18f63b4d5bf)

**Comment by DatL4g** [comment]
Fixed in latest release https://github.com/DatL4g/Burning-Series/releases/tag/v5.3.0

**Comment by operationairstrike** [comment]
This works now.
