### ISSUE TITLE
[Feature Request] Landscape mode usability

### ISSUE THREAD

**Issue by tm-frs** [DATL4G/BurningSeries-Android#72]
**Is your feature request related to a problem? Please describe.**
The app is pretty good to use, except for one annoying thing: When you have the list of episode opened and turn the device into landscape mode, you just get the main menu in landscape (which kinda seems to be intended). That's especially annoying when you've finished an episode and want to start the next one.

**Describe the solution you'd like**
I would really like to have a landscape mode-compatible episode list (or maybe at least some way to see and start the episodes in landscape mode, if there's a good reason for the current behaviour)

**Comment by DatL4g** [comment]
I don't quite understand your request.
The episode list is visible in landscape mode and there is a button in the bottem right corner which directly loads the next epsiode.

Maybe you could elaborate it a bit more or show a screenshot or video what you mean exactly.

**Comment by tm-frs** [comment]
Here's a Screen Recording in which you can see that as soon as I turn my device into landscape mode, it goes back and I cannot access the episode list. However, upon turning back to portrait mode, it will show the episode list again

https://github.com/DatL4g/Burning-Series/assets/82935664/08bc7261-8a15-4892-9f65-e93e7016a9d9

**Comment by DatL4g** [comment]
Alright now I understand, probably same as #67.  
The series screen is not visible because the screen is detected as large but is not large enough.

**Comment by DatL4g** [comment]
Please update to https://github.com/DatL4g/Burning-Series/releases/tag/v5.4.0 and check if the issue still exists

**Comment by tm-frs** [comment]
Seems to be fixed now, thank you
