### ISSUE TITLE
Activating an episode with the desktop App

### ISSUE THREAD

**Issue by deGoatGorgL** [DATL4G/BurningSeries-Android#78]
First of all I want to thank you a lot for this great app and figured I wanted to try it on Desktop too, however I ran into the following problem: 
I tried to activate an episode on your desktop app for windows, "Browser wird initialisiert, bitte warten" means I have to wait for the browser to start so I can activate the episode. right? But the browser never gets initialised / started so I'm basically stuck in the progress, is it because of my browser (Arc, based on Chromium) or do I have to give some permissions to your app? 
(I do have the chromium extensions installed for my Arc Browser)

What I've also noticed, in the App my Cursor seems to vanish for some reason when navigating in the App, it only shows when I'm choosing the season of a TV-Show.

**Comment by DatL4g** [comment]
Activating in the desktop application will be removed in the upcoming `6.0.0` release.

Please download the browser extension instead, enable DoH (with Google, NOT Cloudflare!) in your browser (steps differ on browser, so you have to look it up yourself) and head over to https://bs.to
