### ISSUE TITLE
[BUG] Streams don't activate 

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#79]
**Describe the bug**
Streams don't activate anymore when trying to activate using voe.sx

**To Reproduce**
1. Go to any series
2. Click on any Episode
3. Wait for the activation prompt 
4. Try to activate.
5. "Successfully activated hoster" appears, but watch now button is missing and when you go back to the episode selection it also still isn't activated

**Expected behavior**
Episode should activate.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: OxygenOS 14.0
 - Version 5.5.1

**Additional context**
I've also been having this problem with other hosters every now and then.

**Comment by DatL4g** [comment]
Already on my To-Do list, will check and `6.0.0` may come with more hosters

**Comment by ngelus** [comment]
> Already on my To-Do list, will check and `6.0.0` may come with more hosters

Alright. I'll patiently wait for 6.0.0 then. 😀
