### ISSUE TITLE
[BUG] Login not working with Firefox (Android)

### ISSUE THREAD

**Issue by Le0X8** [DATL4G/BurningSeries-Android#83]
**Describe the bug**
When I want to log in to my GitHub account with Firefox as my default browser, after verifying my identity, it just doesn't leave the GitHub "You are being redirected to the authorized application." page.

**To Reproduce**
1. Go to Settings
2. Press Login
3. Signed in as <user name> -> Continue
4. Nothing happens

**Expected behavior**
A successful login into my GitHub account. 

**Screenshots**

![Screenshot_20240716_225858_Firefox.jpg](https://github.com/user-attachments/assets/c4dbc171-aca8-4e65-96e0-6ca3ce7a704e)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S24
 - OS: Android 13
 - Version 6.0.0

**Additional context**
Everything works as intended using a Chromium-based browser.

**Comment by DatL4g** [comment]
Seems to be intended: https://stackoverflow.com/questions/49397439/appauth-android-https-scheme-work-with-firefox-and-other-browser
