### ISSUE TITLE
[Feature Request]certificate hash?

### ISSUE THREAD

**Issue by friendupright** [DATL4G/BurningSeries-Android#91]
**Is your feature request related to a problem? Please describe.**
I am looking for a certificate hash to verify the installation/apk.

Can you provide it so me and others can verify with appverifier.

Thanks :)

**Describe the solution you'd like**
You could provide the SHA-256 hash of the signing certificate or alternatively distribute on https://accrescent.app/ to solve this issue (but I think just providing the SHA-256 hash of the signing certificate would be easier and faster. 

**Describe alternatives you've considered**
Can't be solved just by me. Sorry... 

**Additional context**
https://github.com/soupslurpr/AppVerifier

https://developer.android.com/studio/publish/app-signing#api-providers

**Comment by DatL4g** [comment]
Here you go:

```
SHA1: 46:AF:26:D1:0D:70:BD:13:C0:C8:5B:65:02:55:E7:9F:59:7E:61:35
SHA256: 41:CF:ED:66:EE:87:7E:85:CC:9E:C0:63:28:A4:C8:09:56:95:FA:21:64:7D:73:36:99:5D:E5:7E:14:AC:97:22
```

Btw you can print it yourself like this:

```
keytool -printcert -jarfile app.apk
```
