### ISSUE TITLE
[BUG] App crashes immediately on launch (Version 6.1.0, Android)

### ISSUE THREAD

**Issue by Gituser436** [DATL4G/BurningSeries-Android#93]
Description:
In version 6.1.0 of the Android app, the application crashes immediately upon opening. This happens consistently every time I try to launch the app.

Steps to Reproduce:

1. Install version 6.1.0 of the app.

2. Open the app on a device running Android 14.

3. Observe that the app crashes immediately.

Expected Behavior:
The app should launch without crashing.

Environment:

App Version: 6.1.0

OS: Android 14

**Comment by DatL4g** [comment]
Should work as expected on Android 14, tested on Google Pixel 9 Pro and Emulators.

Since it happens before the app fully launches I don't have any logs.
To be able to fix this issue I need the error log, if you don't know how to do this, here a small and easy explanation that should do the job:

- Close the app fully
- Install `adb` on your system
- Connect your smartphone using USB
- In CMD or a terminal (depending on your OS) call: `adb devices`
  - Your device should be listed then
  - If not make sure to follow any instructions popping up on your smartphone
- Then call: `adb logcat -c` to clear previous logs
- Finally call: `adb logcat` and start the app

**Comment by Gituser436** [comment]
I just wanted to follow up and confirm that I have tested the feature on three Samsung devices: two smartphones and one tablet. All devices are running One UI 6.1, and unfortunately, the issue persists across all of them. The feature still doesn't work as expected.

Additionally, I’ve tried clearing the app's cache, deleting the data, and even uninstalling and reinstalling the app, but the issue remains unresolved.

**Comment by Gituser436** [comment]
> Should work as expected on Android 14, tested on Google Pixel 9 Pro and Emulators.
> 
> Since it happens before the app fully launches I don't have any logs. To be able to fix this issue I need the error log, if you don't know how to do this, here a small and easy explanation that should do the job:
> 
>     * Close the app fully
> 
>     * Install `adb` on your system
> 
>     * Connect your smartphone using USB
> 
>     * In CMD or a terminal (depending on your OS) call: `adb devices`
>       
>       * Your device should be listed then
>       * If not make sure to follow any instructions popping up on your smartphone
> 
>     * Then call: `adb logcat -c` to clear previous logs
> 
>     * Finally call: `adb logcat` and start the app

I just wanted to follow up and confirm that I have tested the feature on three Samsung devices: two smartphones and one tablet. All devices are running One UI 6.1, and unfortunately, the issue persists across all of them. The feature still doesn't work as expected.

Additionally, I’ve tried clearing the app's cache, deleting the data, and even uninstalling and reinstalling the app, but the issue remains unresolved.

**Comment by DatL4g** [comment]
As I said nothing I can do here without the logs, tested and works on all my devices.

**Comment by Gituser436** [comment]
> As I said nothing I can do here without the logs, tested and works on all my devices.

|    0.0    0.0    0.0    0.0 |    0    0 1080 2340 | Dim Layer for - WindowedMagnification:0:31#968
12-03 04:38:24.227  1354  1354 D SurfaceFlinger:      DEVICE | 0xb4000077257506a0 | 0100 | RGBA_8888    |    6.0    0.0 1086.0  759.0 |    0 1443 1080 2202 | Application Error: dev.datlag.burningseries#966

**Comment by Gituser436** [comment]
> As I said nothing I can do here without the logs, tested and works on all my devices.

12-03 04:38:28.952  1031  1031 E audit   : type=1327 audit(1733197108.947:6954): proctitle="dev.datlag.burningseries"
12-03 04:38:28.954 30039 30039 E g.burningseries: No implementation found for java.lang.String dev.datlag.burningseries.Sekret.githubClientId(java.lang.String) (tried Java_dev_datlag_burningseries_Sekret_githubClientId and Java_dev_datlag_burningseries_Sekret_githubClientId__Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
12-03 04:38:28.954 30039 30039 D AndroidRuntime: Shutting down VM
12-03 04:38:28.955 30039 30039 E AndroidRuntime: FATAL EXCEPTION: main
12-03 04:38:28.955 30039 30039 E AndroidRuntime: Process: dev.datlag.burningseries, PID: 30039
12-03 04:38:28.955 30039 30039 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String dev.datlag.burningseries.Sekret.githubClientId(java.lang.String) (tried Java_dev_datlag_burningseries_Sekret_githubClientId and Java_dev_datlag_burningseries_Sekret_githubClientId__Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?

**Comment by Gituser436** [comment]
> As I said nothing I can do here without the logs, tested and works on all my devices.

12-03 04:38:28.956  1500 30071 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-03 04:38:28.956  1500  6930 D Debug   : low && ship && 3rdparty app crash, do not dump
12-03 04:38:28.957  1500 30072 W ActivityManager: crash : dev.datlag.burningseries,10768
12-03 04:38:28.957  1500  6930 W ActivityTaskManager:   Force finishing activity dev.datlag.burningseries/.MainActivity

**Comment by Gituser436** [comment]
> As I said nothing I can do here without the logs, tested and works on all my devices.

12-03 04:38:29.000  5827  5827 I SDHMS:BarTender:Gatherer:AppError: update AppError : uid=10768, pkg=dev.datlag.burningseries, errorType=crash

**Comment by DatL4g** [comment]
Does the same happen when you uninstall the app and then install the 6.0.0 one?

**Comment by Gituser436** [comment]
> Does the same happen when you uninstall the app and then install the 6.0.0 one?

 Version 6.0 runs perfectly!

**Comment by DatL4g** [comment]
I added `android-samsung` to the releases, that should work for you

**Comment by Gituser436** [comment]
> Does the same happen when you uninstall the app and then install the 6.0.0 one?

 Version 6.0 runs perfectly! 

> I added `android-samsung` to the releases, that should work for you

It works. Thank you very much for the quick support.

**Comment by Panagel** [comment]
[Uploading log.txt…]()

Pixel 6a
Android 14

Same behavior

**Comment by DatL4g** [comment]
@Panagel use the Samsung version as well.

It's a Kotlin bug which has already been reported

**Comment by ngelus** [comment]
Also didn't work on my OnePlus 11.
The Samsung release die work tho 👍

**Comment by High-village** [comment]
ye app only crashes since 6.1 cant use it anymore

**Comment by High-village** [comment]
ok so the samsung version works on my rog phone, on the TV tho the normal signed one is fine. I noticed on the tv everything works okay so far just not the home screen basically bc I think you made it so only touch inputs are recognized there to scroll through the newest stuff. so you have to directly know which series you wanna watch and search for it directly then you can navigate again on the page of the series itself.
