### ISSUE TITLE
[BUG] Navigation on Android TV 11 not working properly

### ISSUE THREAD

**Issue by normand198** [DATL4G/BurningSeries-Android#96]
In version 6.1.0 I can no longer activate/click on any element outside of the search bar. Neither with TV remote nor with external mouse. So it's not possible to use favorites or any other suggestion on the start page.
To continue watching a series I have to use the search bar to search for a title and only then I can navigate the episodes.

In version 6.0.0 I could use an external mouse to control everything in the app. TV remote showed same behavior as in 6.1.0 but that was fine.

 - Device: Philips OLED 934
 - OS: Android TV 11
 - Version 6.1.0

Tested with android-release-signed.apk and android-samsung.apk

**Comment by DatL4g** [comment]
External mouse should work as before, I didn't change anything regarding that and they behave like tapping on smartphone.

However updates/changes regarding AndroidTV won't be done anymore in this app.
https://github.com/DatL4g/Mimasu will be the new app with dedicated AndroidTV support.
