### ISSUE TITLE
[BUG] Cant switch Season on Amazon Fire TV 

### ISSUE THREAD

**Issue by Knoxyzz** [DATL4G/BurningSeries-Android#97]
**Describe the bug**
You cant switch the season with left down up or right buttons 

**To Reproduce**
1. Go to 'any series with more than 1 season“
2. Click on 'Season 1“
3.  Try to switch to next season or any other

https://github.com/user-attachments/assets/b435ac76-5316-4142-b4f9-9b1f2d1a2087

**Comment by DatL4g** [comment]
AndroidTV related issues won't be addressed in this version anymore 
https://github.com/DatL4g/Mimasu will come with dedicated AndroidTV support

**Comment by Knoxyzz** [comment]
okay sad. Its almost perfectly working just needs to be able to switch seasons :)
